# buildspec-tf-apply.yml
version: 0.2
phases:
  install:
    commands:
      - curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
      - sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
      - sudo apt-get update && sudo apt-get install terraform -y
  build:
    commands:
      - cd terraform
      - terraform apply -auto-approve plan.tfplan
