version: 0.2

phases:
  install:
    commands:
      - echo "Installing Terraform v1.4.6"
      - curl -Lo tf.zip https://releases.hashicorp.com/terraform/1.4.6/terraform_1.4.6_linux_amd64.zip
      - unzip -o tf.zip
      - sudo mv terraform /usr/local/bin/
      - terraform --version
  pre_build:
    commands:
      - echo "Initializing Terraform"
      - cd terraform
      - terraform init -input=false \
          -backend-config="bucket=${ARTIFACT_BUCKET}" \
          -backend-config="key=${STATE_KEY}" \
          -backend-config="region=${AWS_REGION}" \
          -backend-config="dynamodb_table=${LOCK_TABLE}"
  build:
    commands:
      - echo "Formatting & Validating"
      - terraform fmt -check
      - terraform validate
      - echo "Planning"
      - terraform plan -out=plan.tfplan

artifacts:
  files:
    - terraform/plan.tfplan

cache:
  paths:
    - "~/.terraform.d/plugin-cache/*"
