version: 0.2
# Updated buildspec for proper terraform directory handling

phases:
  install:
    commands:
      - echo "Installing Terraform v1.4.6"
      - curl -Lo terraform.zip https://releases.hashicorp.com/terraform/1.4.6/terraform_1.4.6_linux_amd64.zip
      - unzip -o terraform.zip -d /usr/local/bin
      - chmod +x /usr/local/bin/terraform
      - terraform --version

  pre_build:
    commands:
      - echo "Initializing Terraform"
      - cd terraform
      - terraform init -input=false -backend-config=backend.hcl

  build:
    commands:
      - echo "Formatting & Validating"
      - terraform fmt
      - terraform validate
      - echo "Planning"
      - terraform plan -out=plan.tfplan

artifacts:
  base-directory: terraform
  files:
    - plan.tfplan

cache:
  paths:
    - "~/.terraform.d/plugin-cache/*"
