version: 0.2

phases:
  install:
    commands:
      - echo "Installing Terraform v1.4.6"
      - curl -Lo terraform.zip https://releases.hashicorp.com/terraform/1.4.6/terraform_1.4.6_linux_amd64.zip
      - unzip -o terraform.zip -d /usr/local/bin
      - chmod +x /usr/local/bin/terraform
      - terraform --version

  pre_build:
    commands:
      - echo "Retrieving the plan artifact"
      - cp $CODEBUILD_SRC_DIR_PLANOUTPUT/plan.tfplan terraform/
      - echo "Initializing Terraform with remote state"
      - cd terraform
      - terraform init -input=false -backend-config=bucket=${ARTIFACT_BUCKET} -backend-config=key=${STATE_KEY} -backend-config=region=${AWS_REGION} -backend-config=dynamodb_table=${LOCK_TABLE} -reconfigure

  build:
    commands:
      - echo "Applying Terraform"
      - terraform apply -auto-approve plan.tfplan

cache:
  paths:
    - "~/.terraform.d/plugin-cache/*"
